#!/usr/bin/python

import argparse
import os

args_parser = argparse.ArgumentParser()
args_parser.add_argument('--file', type=str, help="Path for your file")

args = args_parser.parse_args()

os.system(f'g++ {args.file}')
os.system(f'./a.out')
os.system('rm a.out')